### ISSUE TITLE
[Feat]: Implementing main page user flows

### ISSUE THREAD

**Issue by he2e2** [he2e2/oho#11]
## ✅ TODO
- [x] tab, select, search를 입력 받아 리스트 페이지로 정보 전달
- [x] searchBar 엔터, 클릭 이벤트 추가 
- [x] 지역 카드 선택 시, 리스트 페이지로 지역 값만 전달
- [x] 드롭 박스 밖 영역 선택 시, 드롭 박스 사라지게 하기
