### ISSUE TITLE
[refactor]: Overall refactoring

### ISSUE THREAD

**Issue by he2e2** [he2e2/oho#25]
## ✅ TODO
- [x] 홈페이지 주소가 긴 경우
- [x] ios 환경 검색바 크기 조절
- [x] 인기 지역 UI/UX 개선
- [x] 상세 정보 정보 필터링
